name: Sequential Jobs And Outputs

on:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest

    # job1の外側へ公開する値
    # ${{ steps.<渡し元のstep_id>.outputs.<output_name> }}となっていて、そのstep_idの値がわたるようになっている
    outputs:
      job1_message: ${{ steps.create_message.outputs.message }}
      job1_number: ${{ steps.create_number.outputs.number }}

    steps:
      - name: J1 - S1 Create message
        id: create_message
        run: |
          echo "J1-S1: 値を作成します"

          # このstepのoutputとして message を設定
          # ステップ間の値の渡しは、echo "name=value" >> "$GITHUB_OUTPUT" で行う
          echo "message=Hello from job1" >> "$GITHUB_OUTPUT"

      - name: J1 - S2 Receive value from previous step
        run: |
          echo "J1-S2: 前のstepから受け取った値"
          # ステップ間の値の受け取りは、steps.<渡し元のstep_id>.outputs.<output_name> で行う
          echo "message = ${{ steps.create_message.outputs.message }}"

      - name: J1 - S3 Create number
        id: create_number
        run: |
          # ステップ間の値の渡しは、echo "name=value" >> "$GITHUB_OUTPUT" で行う
          echo "J1-S3: 値を作成します"
          echo "number=100" >> "$GITHUB_OUTPUT"

      - name: J1 - S4 Use multiple step outputs
        run: |
          # ステップ間の値の受け取りは、steps.<渡し元のstep_id>.outputs.<output_name> で行う
          echo "message = ${{ steps.create_message.outputs.message }}"
          echo "number  = ${{ steps.create_number.outputs.number }}"
          # このステップでは単に値を表示しているだけ。次のjob2への値渡しは、job1.outputsのところ。


  job2:
    runs-on: ubuntu-latest

    # job1完了後に実行
    # job1のoutputを参照するためにも必要
    needs: job1

    # job2からjob3へ渡す値
    # ${{ steps.<渡し元のstep_id>.outputs.<output_name> }}となっていて、そのstep_idの値がわたるようになっている
    outputs:
      job2_message: ${{ steps.convert_message.outputs.converted_message }}
      job2_number: ${{ steps.calculate_number.outputs.calculated_number }}

    steps:
      - name: J2 - S1 Receive job1 outputs
        run: |
          echo "job1から受け取った値"
          # ジョブ間の値の受け取りは、needs.<渡し元のjob_id>.outputs.<output_name> で行う
          echo "message = ${{ needs.job1.outputs.job1_message }}"
          echo "number  = ${{ needs.job1.outputs.job1_number }}"

      - name: J2 - S2 Convert message
        id: convert_message
        env:
          JOB1_MESSAGE: ${{ needs.job1.outputs.job1_message }}
        run: |
          # job1から受け取った文字列を加工
          # 例えば、"Hello from job1" を "Hello from job1 -> processed by job2" に変換しているイメージ
          converted_message="${JOB1_MESSAGE} -> processed by job2"
          # 再びステップ間の値渡しのために、echo "name=value" >> "$GITHUB_OUTPUT" の形式で出力
          echo "converted_message=${converted_message}" >> "$GITHUB_OUTPUT"

      - name: J2 - S3 Calculate number
        id: calculate_number
        env:
          JOB1_NUMBER: ${{ needs.job1.outputs.job1_number }}
        run: |
          # job1から受け取った文字列->数値をbashで計算
          calculated_number=$((JOB1_NUMBER + 50))
          # 再びステップ間の値渡しのために、echo "name=value" >> "$GITHUB_OUTPUT" の形式で出力
          echo "calculated_number=${calculated_number}" >> "$GITHUB_OUTPUT"

      - name: J2 - S4 Check outputs in same job
        run: |
          echo "同じjob内の前のstepから受け取った値"
          # ステップ間の値の受け取りは、steps.<渡し元のstep_id>.outputs.<output_name> で行う
          echo "message = ${{ steps.convert_message.outputs.converted_message }}"
          echo "number  = ${{ steps.calculate_number.outputs.calculated_number }}"
          # このステップでは単に値を表示しているだけ。次のjob3への値渡しは、job2.outputsのところ。


  job3:
    runs-on: ubuntu-latest
    needs: job2

    steps:
      - name: J3 - S1 Receive job2 outputs
        run: |
          echo "job2から受け取った値"
          # ジョブ間の値の受け取りは、needs.<渡し元のjob_id>.outputs.<output_name> で行う
          echo "message = ${{ needs.job2.outputs.job2_message }}"
          echo "number  = ${{ needs.job2.outputs.job2_number }}"

      - name: J3 - S2 Use values through environment variables
        env:
          RECEIVED_MESSAGE: ${{ needs.job2.outputs.job2_message }}
          RECEIVED_NUMBER: ${{ needs.job2.outputs.job2_number }}
        run: |
          echo "envへ格納した値"
          echo "RECEIVED_MESSAGE=${RECEIVED_MESSAGE}"
          echo "RECEIVED_NUMBER=${RECEIVED_NUMBER}"


  job4:
    # needsがないため、job1と並列に開始される
    runs-on: ubuntu-latest

    steps:
      - name: J4 - S1 Create independent value
        id: create_job4_value
        run: |
          echo "job4_value=This value exists only in job4" >> "$GITHUB_OUTPUT"

      - name: J4 - S2 Receive value from previous step
        run: |
          echo "job4内のstep間で受け取った値"
          # ステップ間の値の受け取りは、steps.<渡し元のstep_id>.outputs.<output_name> で行う
          echo "${{ steps.create_job4_value.outputs.job4_value }}"
      # ただし、job4の値はjob1/job2/job3からは参照していないです。