name: Parallel Jobs
on: push
jobs: # jobsに複数のジョブを定義すると、それらは並列に実行される。
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: J1 - S1
        run: echo "This is J1-S1" && echo "$(date)" && sleep 10 && echo "END J1-S1" && echo "$(date)"
      - name: J1 - S2
        run: echo "This is J1-S2" && echo "$(date)" && sleep 10 && echo "END J1-S2" && echo "$(date)"
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: J2 - S1
        run: echo "This is J2-S1" && echo "$(date)" && sleep 10 && echo "END  J2-S1" && echo "$(date)"
      - name: J2 - S2
        run: echo "This is J2-S2" && echo "$(date)" && sleep 10 && echo "END J2-S2" && echo "$(date)"
  job3:
    runs-on: ubuntu-latest
    steps:
      - name: J3 - S1
        run: echo "This is J3-S1" && echo "$(date)" && sleep 10 && echo "END J3-S1" && echo "$(date)"
      - name: J3 - S2
        run: echo "This is J3-S2" && echo "$(date)" && sleep 10 && echo "END J3-S2" && echo "$(date)"