name: Static analysis
on: 
  push:
    paths:
      - '.github/workflows/*.yml' # workflowsディレクトリ直下のワークフローファイルの変更をトリガーにする
      - '.github/workflows/*.yaml'
defaults: # デフォルトシェルの設定 = bashを選択
  run:
    shell: bash
concurrency: # ワークフローの同時実行の制御 = 同じグループのワークフローがすでに実行中の場合、現在のワークフローをキャンセルする
  group: ${{ github.workflow }}-${{ github.ref }} # 同じワークフローかつ同じブランチの実行を同じグループにする
  cancel-in-progress: true # 新しくこのワークフローの実行が開始されたら、同じグループで実行中の古いワークフローをキャンセルする
jobs:
  lint:
    name: Static Analysis - Actionlint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Run actionlint with Docker
        run: |
          echo 'Checking out repository...'
          echo 'Analyzing workflow files in .github/workflows/ directory with Docker'
          docker run --rm -v "${PWD}:${PWD}" -w "${PWD}" rhysd/actionlint:latest .github/workflows/*.yml

# このワークフローはinvalid.ymlに対し、actionlintを使って静的解析を行うものです。
# invalid.ymlはわざと、jobsもstepsも定義しない、無効なワークフローにしています。
# 静的解析ワークフローでエラーがでることを確認するためです。