name: Environments
on:
  workflow_dispatch: # 手動トリガーのみとする
    inputs:
      environment-name:
        description: 'Select the environment to deploy to (デプロイする環境を選択してください)'
        required: true
        default: 'stg'
        type: choice
        options:
          - stg
          - test
jobs:
  print_secrets_variables:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment-name }} # 利用する環境(Environment)を指定
    env:
      ENVIRONMENT_NAME: ${{ inputs.environment-name }} # ジョブLvの環境変数として利用
      COMMON_SECRETS: ${{ secrets.COMMON_SECRETS }} # 環境変数によらないシークレットを利用
      COMMON_VARIABLES: ${{ vars.COMMON_VARIABLES }} # 環境変数によらないvariablesを利用
      ENVIRONMENT_SECRETS: ${{ secrets.ENVIRONMENT_SECRETS }} # 環境変数によるシークレットを利用
      ENVIRONMENT_VARIABLES: ${{ vars.ENVIRONMENT_VARIABLES }}
    steps:
      - name: Print selected environment (選択された環境を表示)
        run : |
          echo "Selected environment= ${{ inputs.environment-name }}"
          echo "COMMON_SECRETS= ${{ secrets.COMMON_SECRETS }}"
          echo "COMMON_SECRETS is ${COMMON_SECRETS:0:1} ${COMMON_SECRETS#?}"
          echo "COMMON_VARIABLES= ${{ vars.COMMON_VARIABLES }}"
          echo "ENVIRONMENT_SECRETS= ${{ secrets.ENVIRONMENT_SECRETS }}"
          echo "ENVIRONMENT_SECRETS is ${ENVIRONMENT_SECRETS:0:1} ${ENVIRONMENT_SECRETS#?}"
          echo "ENVIRONMENT_VARIABLES= ${{ vars.ENVIRONMENT_VARIABLES }}"
      - name: Print stg environment secrets and variables (stg環境のシークレットと変数を表示)
        if: ${{ inputs.environment-name }} == 'stg' # 環境がstgの場合のみ実行
        run : |
          echo "STG_ENV_ONLY_SECRETS= ${{ secrets.STG_ENV_ONLY_SECRETS }}"
          echo "STG_ENV_ONLY_SECRETS is ${STG_ENV_ONLY_SECRETS:0:1} ${STG_ENV_ONLY_SECRETS#?}"
          echo "STG_ENV_ONLY_VARIABLES= ${{ vars.STG_ENV_ONLY_VARIABLES }}"
      - name: Print test environment secrets and variables (test環境のシークレットと変数を表示)
        if: ${{ inputs.environment-name }} == 'test' # 環境がtestの場合のみ実行
        run : |
          echo "TEST_ENV_ONLY_SECRETS= ${{ secrets.TEST_ENV_ONLY_SECRETS }}"
          echo "TEST_ENV_ONLY_SECRETS is ${TEST_ENV_ONLY_SECRETS:0:1} ${TEST_ENV_ONLY_SECRETS#?}"
          echo "TEST_ENV_ONLY_VARIABLES= ${{ vars.TEST_ENV_ONLY_VARIABLES }}"