name: Hello #ワークフロー名
on:
  push: #イベント (起動方法1 プッシュされたときに起動の意味)
  workflow_dispatch: #イベント (起動方法2 手動実行時に起動の意味)
    inputs: #手動実行のときの入力値(配列)の定義
      name: #入力値の名前
        type: string #入力値の型
        default: YourName
        required: true #入力値が必須であることを示す
        description: 'Your name(Required True)' #入力値の説明
        
    # branches:
    #   - main #mainブランチにプッシュされたとき
jobs:   # ジョブの定義(配列)
  hello:  # ジョブ名
    runs-on: ubuntu-latest # ジョブの実行環境
    steps: # ステップの定義(配列)
      - name: Hello world # 最初のステップ名
        run: echo "Hello ${{ inputs.name }}" # コマンド(echoコマンドを実行する時に引数を表示する。${{ inputs.name }}は手動実行のときの入力値を参照する)
      - uses: actions/checkout@v4 # 2番目のステップ (リポジトリのコードをチェックアウトするアクション)